spring.application.name=core

spring.datasource.url=jdbc:postgresql://localhost:5432/backend
spring.datasource.username=backend
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

server.port=8080
